# Generated by Django 3.1.4 on 2020-12-17 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_auto_20201217_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='auto_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
